### ISSUE TITLE
Valid parameter type from check callback is misleading

### ISSUE THREAD

**Issue by deckar01** [sweetcaptcha/sweetCaptcha-sdk-js#1]
```sweetcaptcha.api('check', {sckey: formSckey, scvalue: formScvalue}, function(err, valid) { ... })```

I expected the ```valid``` parameter to be a boolean not a string. There is no documentation explaining this is a string, and using the name ```valid``` implies it is a boolean value.

```
sweetcaptcha.api('check', {sckey: formSckey, scvalue: formScvalue}, function(err, valid) {
  if(valid) {
    // Do something
  }
});
```
This would likely pass a code review even though it accepts invalid captchas.

I would recommend documenting the parameter types and changing the readme to ```sweetcaptcha.api('check', {sckey: formSckey, scvalue: formScvalue}, function(err, results) { ... })``` to clarify.

The next step is to remove the overloaded ```api()``` method in favor of convenience methods that curate the results of specific API requests. Converting a string to a boolean value is precisely the type of task that I expect an SDK to do for me.

**Comment by ppham27** [comment]
+1 to this. I spent half an hour before realizing that `valid` is a string. At the very least, it should be in the documentation.

**Comment by sagish** [comment]
it's described on https://github.com/sweetcaptcha/sweetCaptcha-sdk-js/blob/master/example.js
readme updated nonetheless
